### PR TITLE
Testing GitHub PR builder with integration tests

### PR DESCRIPTION
**Pull request by jkopriva**
Please do not merge! This PR is just for testing purposes.

### CODE REVIEW

**Comment by jkopriva** [comment]
testPR

**Comment by jkopriva** [comment]
testPR

**Comment by nickboldt** [comment]
You're writing integration tests for these tycho plugins?

**Comment by jkopriva** [comment]
The tests for maven are more or less complete, right now I am setting up connection between GitHub and Central CI. Should I use different repo on GitHub?

**Comment by jkopriva** [comment]
I am sorry, I will switch to repo: https://github.com/jbosstools/jbosstools-central , closing PR as invalid.

**Pull request closed without merging**
