### PR TITLE
Add a parameter to skip the generation of buildinfo.json

### PR DESCRIPTION
**Pull request by MarkZ3**
This is useful for users who don't need this extra information in the
repository.

Signed-off-by: Marc-Andre Laperle <malaperle@gmail.com>

### CODE REVIEW

**Comment by mickaelistria** [comment]
Merged.
Should be available in 0.23.2-SNAPSHOT later today.
Thanks

**Comment by MarkZ3** [comment]
Thanks! I assume the next release will follow the next Tycho release? (Because of the matching version numbers)

**Comment by mickaelistria** [comment]
Yeah, it's more or less the plan, but I also can release those next week if you remind me of it.

**Comment by MarkZ3** [comment]
Would now be a good time? :)

**Comment by mickaelistria** [comment]
jbosstools-maven-plugins 0.23.2 was just released.
It's available on JBoss Maven repository.

**Comment by MarkZ3** [comment]
Works great! Thank you very much!

**Pull request merged**
