### PR TITLE
JBDS-3361 fix GenerateRepositoryFacadeMojo so it works w/ new path conventions from JBDS-3208 >> master

### PR DESCRIPTION
**Pull request by nickboldt**

### CODE REVIEW

**Comment by mickaelistria** [comment]
I think it's NOT a good idea to have our repo URL convention intruding in this mojo. Can't this URL suffix be set in parent pom or pom.xml?

**Comment by nickboldt** [comment]
We could add a configuration item to aggregate/site/pom.xml (in lines 43-57) for jbosstools_site_suffix, which is the variable already used in the parent pom. So, then we would test the raw URL first, and if that fails add in the path segment "latest/all/repo" to test as a backup.

**Comment by mickaelistria** [comment]
Actually, I don't even understand why such a change is required. The mojo goes to each site in  listed as <repository> with layout p2 in the hierarchy of pom files, and looks for a buildinfo.json. Why do we need anything more complex? What is the site for which it doesn't suffice?

**Comment by nickboldt** [comment]
All of them, under the new way of publishing.

http://download.jboss.org/jbosstools/builds/staging/jbosstools-base_master/ ... composite site 
http://download.jboss.org/jbosstools/builds/staging/jbosstools-base_master/latest/all/repo/ ... single site w/ buildinfo.json

See also arquilian, aerogear, ... vpe, webservices. This new pattern of build publishing means we automatically get a composite of "build N, build N+1, build N+2" and automated cleanup (never less than 1 build), plus a pointer to the latest one.

**Comment by nickboldt** [comment]
Tested locally and it's happy for everything except the projects which don't have buildinfo.json files (portlet, freemarker, xulrunner).

**Comment by mickaelistria** [comment]
Why not overriding this property https://github.com/jbosstools/jbosstools-build/blob/master/parent/pom.xml#L79 to latest/all/repo ?

**Comment by nickboldt** [comment]
In parent pom on https://github.com/jbosstools/jbosstools-build/blob/master/parent/pom.xml#L79  I've said: "for a single build [stable branch], use latest/all/repo; for a composite of current builds [master branch], use """. 

In aggregate/site/pom.xml, I'm suggesting this: https://github.com/jbosstools/jbosstools-build-sites/pull/180/files

We could simply set <jbosstools_site_suffix>latest/all/repo</jbosstools_site_suffix> in aggregate/site/pom.xml ...  but if we did that, then the aggregate would *always* build against the single latest site, and could fail for nightlies in master while new stuff is being published (eg., when the /latest/ symlink moves).

That's why we have the option to build from the composite (this replaces the old staging and staging.previous). It's more stable when current and previous bits are available concurrently. (cc: @dgolovin )

**Comment by mickaelistria** [comment]
Ok, got it. Still/again this issue, one day, we should count the cost that the failures it did cost and compare it with the amount of effort deployed to try to fix it. I'm not sure it's really a profitable ration.

In that case, it's totally not relevant to pull the buildinfo.json from latest. Indeed, if you have a composite, it means that you delibarately agree to pull content from another site than "latest", so in such case, you don't want the buildinfo.json that's in "latest", but the one from some other site. So in the end, this approach is totally incompatible with the ability to be able to actually detect and document what "upstream" is.

**Comment by maxandersen** [comment]
something I'm not following here:

a) same as mistria - looks very wrong any of our conventions need to be encoded in these mojos. That is adding possible bad assumptions into the plugin

b) why is the N, N+1, N+2 even involved in our normal build ? in a normal build there should be *one* clear path where things are from. Nothing composited together from past releases.

**Comment by nickboldt** [comment]
re: (a) -- removed from mojo, moved to pom, as indicated above.

re: (b) -- https://issues.jboss.org/browse/JBIDE-15482?focusedCommentId=12974385&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-12974385 Please talk to @dgolovin as he's the one that has consistently reported this problem and for which I've tried a few times to design a better approach.

**Comment by nickboldt** [comment]
"Indeed, if you have a composite, it means that you delibarately agree to pull content from another site than "latest", so in such case, you don't want the buildinfo.json that's in "latest", but the one from some other site. "

No. Composite site simply provides a way to fall back for nightlies from master, so that a BUILD will not fail to resolve dependencies when the upstream site disappears (eg., B123 replaced by B124).

Fetching of buildinfo.json is still relevant, and you still want it to point to latest build. 

But since master moves frequently, this allows us to mitigate failures (see JBIDE-15482). For 4.3.mars stable branch, we simply point at the SINGLE latest build, not the composite. 

This is very much akin to what I used to do w/ the composite sites:

Old ones:
https://github.com/jbosstools/jbosstools-download.jboss.org/blob/master/jbosstools/builds/staging/_composite_/core/master/compositeArtifacts.xml (uses staging and staging.previous - 2 sites composited)
https://github.com/jbosstools/jbosstools-download.jboss.org/blob/master/jbosstools/builds/staging/_composite_/core/4.3.mars/compositeArtifacts.xml (uses only staging - single site)

New, simpler ones:
https://github.com/jbosstools/jbosstools-download.jboss.org/blob/master/jbosstools/mars/snapshots/builds/_composite_/core/master/compositeArtifacts.xml (does not use latest/all/repo - 2+ sites composited)
https://github.com/jbosstools/jbosstools-download.jboss.org/blob/master/jbosstools/mars/snapshots/builds/_composite_/core/4.3.mars/compositeArtifacts.xml (uses latest/all/repo - single site)

**Comment by maxandersen** [comment]
you want buildinfo.json to be retrieved from what it was built from - that is not necessarily latest in all cases.
I don't grok the wish to fall back to nightlies - if we are building for a release we want stuff to *fail* if things are not actually working.

What am I missing ?

**Comment by mickaelistria** [comment]
Also, I agree with @maxandersen on the fact that this approach makes that you're basically hardcoding the fact that the build comsumes the latest repo in the composite, whereas all this set up was made to actually use the composite without being able to guarantee what was used for the build.
Let's just deal with it: if we use composite, we can't easily know which buildinfo.json to consume, so let's consume none (or let's avoid composites).

**Comment by nickboldt** [comment]
"we can't easily know which buildinfo.json to consume, so let's consume none (or let's avoid composites)."

So rather than polling the latest upstream builds you'd rather poll none? That means for all nightlies on master we would have NO buildinfo.json data, because most of the time there's more than one entry in the composite sites, eg. [1].

[1] http://download.jboss.org/jbosstools/mars/snapshots/builds/jbosstools-base_master/compositeArtifacts.xml [as I type this, today there's only one build folder in there]

For 4.3.mars (stable builds from jbosstools-4.3.0.*Nx branch) you'd STILL need to pull from *jbosstools-base_master/latest/all/repo/buildinfo.json* instead of *jbosstools-base_master/buildinfo.json* because the URL pattern has changed for mars (but we need to support luna and before, too).

So, yes, I can rename the variable. But it's the path suffix required to find buildinfo.json for a given snapshot build folder, so why not call it the *buildInfoJSON pathSuffix* ? 

How is "leafRepositoryPath" more meaningful, when it talks of a "repository" (which we don't care about - we're only searching for a single json file) and replaces the notion of searching for buildInfoJSON with a simple "leaf" ? -100

**Comment by mickaelistria** [comment]
My general opinion is that we should really avoid those composite sites in general. They introduce more complexity and performance churn than value, since the build failure because of content change don't happen that often (maybe 1 time out of 20? I don't have metrics) and is generally easy to workaround (just re-run).

The change you're doing isn't really related to buildInfo.json per se, it's caused by the fact that we now hit composite instead of plain update-sites. Let's imagine we want to consume the index.html later in this same mojo, then we'll have the same prefix for index.html than buildinfo.json. This prefix is actually the location of the child repository. It is what it is.
Maybe it would be simpler and more sustainable to pick arbitrarily the 1st or last entry of the composite repository, and to log a warning "You're hitting a composite repository, don't trust the buildinfo.json".

**Comment by maxandersen** [comment]
"URL pattern has changed for mars (but we need to support luna and before, too)." ...why ? don't we just use the old approach for luna and doing this going forward or how ?

**Comment by maxandersen** [comment]
I'm getting a bit worried why we are starting to talk about what sounds like very unreliable build chain. Are we sure we building this right if we are not even able to trace back what we built from ? 

I don't have a clear solution but do we agree that it is a problem if our build can't be repeated nor documented (I consider buildinfo.json documentation) reliably ?

**Comment by nickboldt** [comment]
So... after much discussion I think we've settled on the idea that it's OK to use the latest symlink to resolve the upstream buildinfo.json files.

The old variable for this was "LATEST_REPO_DIR" and I renamed it to "buildInfoJSONPathSuffix" to be more clear what it was for; Mickale then suggested we should use "leafRepositoryPath" instead.

Can we decide what we want to call this variable? I'll update this PR and also 
https://github.com/jbosstools/jbosstools-build-sites/pull/180 once we settle on a name everyone likes.

**Comment by mickaelistria** [comment]
What about harcoding it ? I don't see any use case for which one we'd need to override it anyway, and I don't think this change is going to be useful out of JBoss Tools.

**Pull request merged**
