### PR TITLE
JBIDE-22757 bump up to 0.26.0-SNAPSHOT and...

### PR DESCRIPTION
**Pull request by nickboldt**
JBIDE-22757 bump up to 0.26.0-SNAPSHOT and depend on Tycho 0.26.0-SNAPSHOT instead of 0.25.0

### CODE REVIEW

**Comment by mickaelistria** [comment]
Should we release a 0.25.1 ? Or is it fine to stay with 0.25.0 as long as we're using Tycho 0.25.
I don't think we're going to move to Tycho 0.26 very soon so we should make sure we remain able to include changes as long as we're using Tycho 0.25.0

**Comment by nickboldt** [comment]
Considering how few changes [1] have happened since 0.25.0, I'd say yes - release a 0.25.1 - but only if we know 0.26 is far away. Any idea when 0.26 is scheduled? 

[1] https://github.com/jbosstools/jbosstools-maven-plugins/commits/master

**Comment by mickaelistria** [comment]
Not idea of when Tycho 0.26 is planned. Feel free to ask on their mailing-list.

**Comment by nickboldt** [comment]
0.26.0 is released. Merged to master.

**Comment by nickboldt** [comment]
Note, this PR was incorrectly titled. Should have ref'd https://issues.jboss.org/browse/JBIDE-22673

**Pull request closed without merging**
