### PR TITLE
JBIDE-19024: Fixed and enhanced source artifacts mirroring.

### PR DESCRIPTION
**Pull request by tkleszczynski**
1. Fixed mirroring of source artifacts using Tycho 0.22.0
2. Versions of mirrored source artifacts are the same as versions
corresponding code artifacts.
3. Support for mirroring feature sources.

### CODE REVIEW

**Comment by mickaelistria** [comment]
I like the feature you're trying to provide, and I'd be glad to integrate it. I added inline a few questions and remarks.
On a general comment, I believe your suggested approach is very close to better support for multiple versions, instead of artifactId, we could think of using a artifactId/version couple. Using Tycho's DefaultArtifactKey class as entry for the various sets would probably be enough.

**Comment by tkleszczynski** [comment]
Hi, I added support for mirroring sources for multiple versions of artifacts as you suggested.

**Comment by mickaelistria** [comment]
that seems pretty cool! See inline a small comment about a potential typo.
Could you also please squash both your commit as a single one and use "push --force" on your branch to update this PR with a single commit? This makes review and history reading easier.

**Comment by mickaelistria** [comment]
I merged this change that seems good to me. Note that since we (JBoss Tools) are not users of this feature that mirror sources, I've not actually tested it in real scenario.

**Pull request merged**
