### PR TITLE
JBIDE-19718: failbackToChild property + default value

### PR DESCRIPTION
**Pull request by mickaelistria**

### CODE REVIEW

**Comment by nickboldt** [comment]
If this works, it seems good (less code = better code).

However, you called the variable "failbackToChild", not "fallbackToChild". Was that intentional, or just a font-fault faux-pas? (i ~= l )

**Comment by mickaelistria** [comment]
Thanks for the review. I fixed the variable name to fallbackToChild.

**Comment by nickboldt** [comment]
This worked when I built it locally and ran a build of `mvn install -Pmaximum -Pfetch-source-zips -f jbosstools-build-sites/aggregate/site/pom.xml`.

However, I then re-ran it using `<fallbackToChild>woop/de/doop</fallbackToChild>` and it still worked. It should have failed. Or did it fallback silently? There was nothing in the log.

So... seems the value passed in from the pom is being ignored.

Oh, and you missed two more occurrences of "failback" on line 738:

https://github.com/jbosstools/jbosstools-maven-plugins/pull/40/files#diff-1065710c66c369fc43a2cbd90d2a6885R738

So, I'm +1 to apply this but need a better test to verify that commandline / pom vars are being correctly passed in.

**Comment by nickboldt** [comment]
Once your new variable works, we can replace this with something better:

https://github.com/jbosstools/jbosstools-build-sites/commit/7b2308a3386d82e7a19e5e53a00be6399df07f3d

**Comment by mickaelistria** [comment]
> This worked when I built it locally and ran a build of |mvn install 
> -Pmaximum -Pfetch-source-zips -f 
> jbosstools-build-sites/aggregate/site/pom.xml|.However, I then re-ran 
> it using |<fallbackToChild>woop/de/doop</fallbackToChild>| and it 
> still worked. It should have failed. Or did it fallback silently? 
> There was nothing in the log.
>
As name mentions, this is a fallback. So when the buildinfo.json 
directly exist in the reference repositories, it's not used at all.
I believe you command has consumed directly the repo/buildinfo.json, 
without needing to use the fallback in any case.

**Comment by nickboldt** [comment]
Hmm. OK, then I guess +1 is in order. Pu-pu-push it!

**Comment by mickaelistria** [comment]
Rebased and merged as d0533cd

**Pull request closed without merging**
